# Generated by Django 4.0.2 on 2022-02-21 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0002_auto_20220219_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='item',
            name='mainimage',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
