# Generated by Django 4.0.2 on 2022-02-21 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0002_admin_destination_review_delete_item'),
        ('catalogue', '0003_alter_item_images_alter_item_mainimage'),
    ]

    operations = [
    ]
