# Generated by Django 4.0.2 on 2022-02-23 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0005_item_remove_destination_description'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Item',
        ),
        migrations.RemoveField(
            model_name='review',
            name='review',
        ),
        migrations.AddField(
            model_name='destination',
            name='description',
            field=models.TextField(max_length=3500, null=True),
        ),
        migrations.AddField(
            model_name='destination',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='destination',
            name='location',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='rate',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Best'), (2, 'good'), (3, 'okay'), (4, 'bad'), (5, 'worse')], null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='text',
            field=models.CharField(blank=True, max_length=3000),
        ),
    ]
