# Generated by Django 4.0.2 on 2022-04-06 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0009_recommendation'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='average_rate',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True),
        ),
        migrations.DeleteModel(
            name='Recommendation',
        ),
    ]
