# Generated by Django 4.0.2 on 2022-04-06 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0010_destination_average_rate_delete_recommendation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='location',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
