# Generated by Django 3.2.12 on 2022-04-16 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0009_ocrimage'),
        ('catalogue', '0011_alter_destination_location'),
    ]

    operations = [
    ]
